# Generated by Django 5.1.1 on 2024-11-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A_Musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Album_release_Date', models.DateField(auto_now_add=True, null=True)),
                ('Rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True)),
                ('Musician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_Musician.musicianmodel')),
            ],
        ),
    ]
